### ISSUE TITLE
ValueError: Wrong ROIs input format: unfamiliar shape.

### ISSUE THREAD

**Issue by foustoukosg** [rochefort-lab/fissa#148]
Hello, 

I am trying to run FISSA on my Suite2p extracted data and I get pretty fast this error:

**ValueError: Wrong ROIs input format: unfamiliar shape.**

Do you have any idea of what might be causing this? 

Thank you very much in advance for your time and help.

Best,
Georgios

**Comment by swkeemink** [comment]
Hi @foustoukosg ,

Thanks for bringing this to our attention. We are actually working out some bugs with changes in the suite2p code which we have to adjust for (see  #147), so might have to do with that. Are you able to run any of our example notebooks?

A couple of questions:
-    What OS are you on, and what do you use to manage your python environment (e.g. conda)?
-   What version of Python and Suite2P are you using?
-   Could you share with us the output of conda env list and pip freeze for your environment?

Sander

**Comment by foustoukosg** [comment]
Hello,

I am using Python 3.7.7 on Windows 10 with Suite2p version installed 0.9.3. I am using Conda for python environment.

Actually I have looked more into the FISSA code and i think i managed to pin out where exactly the problem is coming from. To my understanding the error I get is caused by the way FISSA is reading the tiff stack of the Suite2p registered frames. Especially your function:

**image2array**

of the **datahandler.py** 

the command:

**tifffile.imread(image)**

Instead or reading the whole stack of the tiff file (usually for suite2p this is 500 if you put reg_tiff option as true) is reading only the first frame of the stuck. Thus, at the later stage an error is raised by FISSA cause ROIs structure and the data image structure does not match.

Interestingly enough, if i use the data.bin file that is also written by suite2p during registration back to tiff with my own code (using the TiffWritter of the tifffile package) the problem is solved and FISSA seems to be running normally. 

I hope this helps a bit more the debugging process and thanks a lot for your open FISSA code. 

Best,
Georgios

**Comment by swkeemink** [comment]
Excellent, thanks for the help from your side! This will certainly be helpful in debugging and solving this for future users.

I'll leave this issue open until we have fixed this in our own actual code too.

**Comment by swkeemink** [comment]
I have reproduced this error, and am working on updating the general suite2p implementation in #150

**Comment by swkeemink** [comment]
@foustoukosg , out of interest and usefulness, could you share your code for interacting with the data.bin file?

There should actually be no need to save them as a tiff, you could just interface fissa with the data.bin directly.

**Comment by foustoukosg** [comment]
Hello, 

Sure. You can here attach the part of my code doing this conversion (saving a session to tiff stacks of 1000 frames):

 `mouseName =         #the mouse flag

  sessionDate =      #the date of the imaging

  binFile = PathToBinFile

  tiffSavePath = SavePath #final saving path

  Lx = 512 # that's my imaging pixel size
  Ly = 512

  nbytestoread = 2*Lx*Ly

  file = -1

  NumOfFrames =       #you need to add here the total number of frames

  #I am saving the tiff files to chuncks of 1000 to avoid huge tiff files (my sessions are pretty long)

  movie = np.zeros((1000, Ly, Lx), dtype = 'int16')

  with open(binFile, 'rb') as binary_file:

          for cframe in range(NumOfFrames):   #NumberOfFrames here is the total number of frames of that session

              bytesToSeek = int(nbytestoread*(cframe)) # I suppose here that you bin file starts directly
              binary_file.seek(bytesToSeek,0)
              buff = binary_file.read(nbytestoread)
              movie[np.mod(cframe,1000),:,:] = np.reshape(np.frombuffer(buff, dtype = np.int16, offset = 0),(Ly,Lx))

              if (np.mod(cframe,1000) == 999):

                  file += 1

                  fileLen = len(str(file))

                  zeros = str(0) * (4-fileLen) + str(file)

                  print('Doing frame: ' + str(cframe + 1))

                  finalPathToSave =  os.path.join(tiffSavePath, mouseName + '_' + sessionDate + '_' + zeros + '.tif')

                  with TiffWriter(finalPathToSave, bigtiff=True) as tif:
                      tif.save(movie, photometric='minisblack')

                  movie = np.zeros((1000, Ly, Lx), dtype = 'int16')

         # save the remaining frames after the last multiple of 1000's

          file += 1

          fileLen = len(str(file))

          zeros = str(0) * (4-fileLen) + str(file)

          print('Doing frame: ' + str(cframe + 1))

          finalPathToSave =  os.path.join(tiffSavePath, mouseName + '_' + sessionDate + '_' + zeros + '.tif')

          lastFrames = NumOfFrames - (file + 1)*1000

          movieToEnd = movie[0:lastFrames,:,:]

          with TiffWriter(finalPathToSave, bigtiff=True) as tif:
              tif.save(movieToEnd, photometric='minisblack')

          print('Tiff writing has finished..')
`

Yes I thought also that the bin file can be directly used but I did not have the time to change the code so much. What is indeed bizarre is that the Suite2p code is also using the tifffile package to write the frames (if you put the reg_tiff paramater on) as I am using as well. FISSA is reading my frames correctly but not the Suite2P ones

Thanks again a lot for your FISSA code.

Best,
Georgios

**Comment by swkeemink** [comment]
This solution also works and is a bit less of a hassle: https://github.com/MouseLand/suite2p/issues/647

I will implement this in the FISSA examples.

**Comment by swkeemink** [comment]
Our tif reading implementation is now much more robust thanks to #170 so closing this.
