### ISSUE TITLE
Turn iPython notebooks into Binders

### ISSUE THREAD

**Issue by scottclowe** [rochefort-lab/fissa#3]
Binder is a new way of serving Notebooks from a GitHub repository on a remote serve without having to download anything to a local machine.

http://mybinder.org/

**Comment by scottclowe** [comment]
For posterity, I deleted some pre-release comments which were off-topic.

**Comment by scottclowe** [comment]
It looks like Binder is quite easy to set up.
https://mybinder.org/v2/gh/rochefort-lab/fissa/master

Currently it is erroring due to our erroneous multiprocessing requirement, which breaks on Python 3. Once #2 is closed, I think this should work fine.

**Comment by scottclowe** [comment]
Binder still doesn't work, even though we now have Python 3 compatibility.

The problem is, they are seeing our requirements.txt file and installing that, but not installing the requirements for plotting. Seems like we would need to add a Dockerfile to get around this?
https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html

**Comment by scottclowe** [comment]
The alternative option is to make a separate repo which just contains the notebooks we want to have on Binder. That repo would instead specify to install fissa with the plotting option.

**Comment by swkeemink** [comment]
Personally I don't think that it is necessary to do this. It would also be confusing to have a second FISSA repository on the rochefort-lab group. (both for users and future rochefort-lab members).
