### ISSUE TITLE
Add a PyPi tutorial

### ISSUE THREAD

**Issue by swkeemink** [rochefort-lab/fissa#39]
For future updates and programmers it would be good to have a standardized way to push updates to PyPi. Will likely add this to CONTRIBUTING.

**Comment by swkeemink** [comment]
Indeed, that's a better place to put it. CONTRIBUTING is more for general contributions, including non-lab people that want to do a pull request.

**Comment by swkeemink** [comment]
I'll also add information on what the version number means. 
@scottclowe : Just to double check with you, the version naming we are using is Semantic Versioning 2.0.0 (https://semver.org/).

**Comment by scottclowe** [comment]
Yes,  semantic versioning. x.y.z == MAJOR.MINOR.PATCH.

**Comment by scottclowe** [comment]
I believe we can close this, as we have a solid [HOWTO_RELEASE.md](https://github.com/rochefort-lab/fissa/blob/master/HOWTO_RELEASE.md) file now.
